### ISSUE TITLE
Questions about the geometric analysis w.r.t. ReLU activation.

### ISSUE THREAD

**Issue by seunghyukcho** [Animadversio/GAN-Geometry#6]
Thanks for the inspiring work! I have some questions about the geometric analysis, the explanation about "Hessian of a squared distance function is a Riemannian metric tensor".

In previous work, as you mentioned in the related work, the generator is assumed to be smooth function due to the definition of Riemannian metric tensor. So it does not allow ReLU.

In the paper of this repository, there is a sentence that the geometrical analysis of the paper is architecture-agnostic which implies the acceptance of ReLU. However, I can't find any evidence about the argument in the analysis.

For example, in the Hessian related to the LPIPS metric, it is composed with Jacobian of the intermediate feature maps, which needs smoothness assumption on the generator. Furthermore, [the shared link](https://mathoverflow.net/questions/45154/riemannian-metric-induced-by-a-metric) in #1 which is related to the argument has an assumption that the metric should be differentiable, which is also a smoothness assumption.

So can you explain more about why the geometric analysis is architecture-agnostic?

**Comment by Animadversio** [comment]
Thanks so much for noticing our work and our repo. 

In practice, for the image generator, we allow ReLU or Leaky ReLUs. Thus the mapping from latent space to image space $z\to \mathcal I$ is not everywhere differentiable. This is not a problem in practice since the ReLU function only has one point that is non-smooth, so numerically it is impossible to get exactly $0$, so we can compute the Jacobian / metric tensor at almost everywhere in the latent space. But what you said is correct, that at some places (cell border of ReLU) the Jacobian / metric tensor will change non-continuously.

So an interesting open question is how "local" is the metric/hessian information. Since it could change non-continuously, it may not inform us anything outside the "ReLU cell". In practice, in our analysis, it seems this metric/hessian information is surprisingly global in many GANs. Although we also result that the metric can predict distance quantitatively only in a very small region. Though the eigen structure and its qualitative order is more global. 

Hope this explanation helps you! Let me know if there are more questions! Happy to answer you 😸
